# Generated by Django 5.1.2 on 2024-10-25 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comparecars', '0003_remove_comparecaruser_car_one_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comparecar',
            name='title',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
