# Generated by Django 5.1.2 on 2024-10-25 17:35

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comparecars', '0005_alter_comparecar_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='comparecar',
            name='date_added',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
