# Generated by Django 5.1.2 on 2024-10-26 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsarticle',
            name='category',
            field=models.CharField(choices=[('Mobil', 'Mobil'), ('Mobil Bekas', 'Mobil Bekas'), ('Tips and Trick Otomotif', 'Tips and Trick Otomotif'), ('Others', 'Others')], default='Others', max_length=50),
        ),
    ]
