# Generated by Django 5.1.2 on 2024-10-25 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookshowroom', '0003_alter_booking_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
