# Generated by Django 5.1.2 on 2024-10-23 06:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
        ('bookshowroom', '0001_initial'),
        ('comparecars', '0002_comparecaruser_delete_car'),
        ('wishlist', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='bookshowroom',
            field=models.ManyToManyField(related_name='bookshowroom', to='bookshowroom.booking'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='comparecars',
            field=models.ManyToManyField(related_name='comparecars', to='comparecars.comparecaruser'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='wishlist',
            field=models.ManyToManyField(related_name='wishlist', to='wishlist.wishlist'),
        ),
    ]
