# Generated by Django 4.2.4 on 2024-10-22 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='pkb_base',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='car',
            name='pkb_value',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='car',
            name='swdkllj',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='car',
            name='total_levy',
            field=models.FloatField(),
        ),
    ]
