# Generated by Django 4.2.4 on 2024-10-22 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_alter_car_pkb_base_alter_car_pkb_value_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='ucd_id',
        ),
    ]
